version: '3.8'
services:
  backend:
    build:
      context: . # Change context to project root
      dockerfile: backend/Dockerfile # Specify Dockerfile location relative to context
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/code:/code/backend # Add /code/backend to PYTHONPATH
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: grocy_assistant
      POSTGRES_USER: grocy_user
      POSTGRES_PASSWORD: grocy_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
volumes:
  pgdata:
    driver: local
